import { Palette, Package, Printer, Layout, Sparkles } from "lucide-react";

export const allServices = [
  {
    title: "CREATIVE DESIGN",
    id:"creative-design",
    subtitle: "Impact, Identity, and Growth-Oriented Strategic Creative Design",
    icon: <Palette size={24} />,
    content: [
      "At Blackantz Creatives, we believe design is more than visuals—it’s a powerful communication tool. Our creative services are built to transform ideas into meaningful brand experiences that connect with your audience and leave a lasting impact.",
      "We specialize in crafting unique brand identities that reflect your business values and vision. From logo design to complete branding systems, every element is carefully designed to ensure consistency, recognition, and long-term brand growth.",
      "Our expertise extends into high-quality signage and visual communication solutions. Whether it’s indoor displays, outdoor branding, or custom signage, we create designs that attract attention and enhance your brand presence in real-world spaces.",
      "We also offer innovative packaging design solutions that combine aesthetics with functionality. Our approach ensures your products not only look appealing but also stand out in competitive markets, helping you create a strong shelf presence.",
      "Driven by creativity and strategy, our team works closely with clients to deliver tailored solutions that meet business goals. At every stage, we focus on quality, precision, and innovation to help your brand grow, stand out, and succeed.",
    ],
    images: [
      "/SERVICES/CREATIVEDESIGN/10 x 10-cm-Heritage Mothers day.jpg",
      "/SERVICES/CREATIVEDESIGN/A_044.png",
      "/SERVICES/CREATIVEDESIGN/Leafl.jpg",
      "/SERVICES/CREATIVEDESIGN/TM03.JPG",
      "/SERVICES/CREATIVEDESIGN/4 Fold Mockup.jpg",
      "/SERVICES/CREATIVEDESIGN/Heaven Pure_2024_Page1.jpg",
      "/SERVICES/CREATIVEDESIGN/Po-02.png",
      "/SERVICES/CREATIVEDESIGN/flyer mockup profess01.jpg",
      "/SERVICES/CREATIVEDESIGN/42 x 27.6 - Boy 1.jpg",
      "/SERVICES/CREATIVEDESIGN/Identity-01.png",
      "/SERVICES/CREATIVEDESIGN/TM02.JPG",
      "/SERVICES/CREATIVEDESIGN/poster01.jpg",
    ],
  },
  {
    title: "PACKAGING DESIGN",
    id:"packaging-design",
    subtitle:
      "Innovative Packaging Design that Blends Usability and Visual Appeal",
    icon: <Package size={24} />,
    content: [
      "Packaging is more than just a cover—it’s the first impression of your product. At Blackantz Creatives, we design packaging that instantly captures attention and communicates your brand story with clarity and impact.",
      "Our approach combines creativity with strategy to ensure your packaging stands out on shelves and digital platforms alike. Every design is crafted to reflect your brand identity while appealing to your target audience.",
      "We specialize in a wide range of packaging solutions, including boxes, pouches, labels, and custom product packaging. Each design is tailored with precision, balancing visual appeal, usability, and production feasibility.",
      "From concept development to final artwork, we focus on every detail—colors, typography, materials, and finishes—to create packaging that enhances product value and builds customer trust.",
      "With a strong understanding of market trends and consumer behavior, we deliver packaging designs that not only look premium but also drive sales, making your product impossible to ignore.",
    ],
    images: [
      "/SERVICES/PACKAGING/Aakaa_Pouch.jpg",
      "/SERVICES/PACKAGING/Avita Standup.jpg",
      "/SERVICES/PACKAGING/Health Drink_Box.png",
      "/SERVICES/PACKAGING/Health_Box.jpg",
      "/SERVICES/PACKAGING/Health_Pillow Pouch.jpg",
      "/SERVICES/PACKAGING/Kayal_Transprent Pouch.jpg",
      "/SERVICES/PACKAGING/Lingam Pillow Pouch.jpg",
      "/SERVICES/PACKAGING/Maduram Snacks pouch.png",
      "/SERVICES/PACKAGING/Maduram Transprent Pouch.jpg",
      "/SERVICES/PACKAGING/Pillow Pouch.jpg",
    ],
  },
  {
    title: "PRINTING SERVICES",
    id:"priniting-services",
    subtitle:
      "Advanced Printing Services Designed for Quality and Brand Consistency",
    icon: <Printer size={24} />,
    content: [
      "Printing is where design comes to life, and at Blackantz Creatives, we ensure every detail is reproduced with precision and clarity. Our printing services are focused on delivering high-quality results that reflect your brand’s professionalism.",
      "We offer a wide range of printing solutions, including brochures, business cards, posters, packaging, labels, and marketing materials. Each project is handled with care to maintain color accuracy, sharpness, and consistency.",
      "Using advanced printing technology and premium materials, we achieve exceptional finishes that enhance the overall look and feel of your designs. From matte to gloss, textured to specialty finishes, we provide options that suit your brand style.",
      "Our team works closely with you to understand your requirements, ensuring the right paper, size, and print technique are selected for the best outcome. We focus on both aesthetics and functionality to deliver prints that make an impact.",
      "With a commitment to quality, timely delivery, and cost-effective solutions, Blackantz Creatives is your trusted partner for reliable printing services that elevate your brand presence.",
    ],
    images: [
      "/SERVICES/PRINTINGSERVICES/Book.jpg",
      "/SERVICES/PRINTINGSERVICES/Brochure.jpg",
      "/SERVICES/PRINTINGSERVICES/Cover.jpg",
      "/SERVICES/PRINTINGSERVICES/Inshop.jpg",
      "/SERVICES/PRINTINGSERVICES/Inshop Sticker.jpeg",
      "/SERVICES/PRINTINGSERVICES/Standee 01.jpeg.jpg",
      "/SERVICES/PRINTINGSERVICES/Standee 02.jpeg",
      "/SERVICES/PRINTINGSERVICES/Sticker 01.jpg",
      "/SERVICES/PRINTINGSERVICES/Sticker 02.jpg",
      "/SERVICES/PRINTINGSERVICES/Veilce Sticker.jpeg",
    ],
  },
  {
    title: "SIGN BOARD",
    id:"sign-boards",
    subtitle: "Striking Visual Branding and Durable Installation",
    icon: <Layout size={24} />,
    content: [
      "A sign board is more than just identification—it’s a powerful branding tool that creates first impressions and attracts attention. At Blackantz Creatives, we design sign boards that make your business stand out in any environment.",
      "We offer a wide range of signage solutions, including outdoor sign boards, indoor displays, LED signs, acrylic letters, and custom branding installations. Each sign is designed to reflect your brand identity while ensuring maximum visibility.",
      "Our approach combines creative design with durable materials to produce signage that is both visually striking and long-lasting. We focus on clarity, readability, and placement to ensure your message is seen and remembered.",
      "From concept and design to fabrication and installation, we handle the complete process with precision and professionalism. Every detail is carefully executed to deliver a flawless final result.",
      "With a commitment to quality craftsmanship and innovative design, Blackantz Creatives delivers sign board solutions that enhance your brand presence and leave a lasting impression on your audience.",
    ],
    images: [
      "/SERVICES/SIGNAGE/ACP Acyrlic Sign.jpeg",
      "/SERVICES/SIGNAGE/ACP_Sign.jpg",
      "/SERVICES/SIGNAGE/Backlit.jpg",
      "/SERVICES/SIGNAGE/Clipon.jpg",
      "/SERVICES/SIGNAGE/Direction Sign.jpeg",
      "/SERVICES/SIGNAGE/Directory Sign.jpg",
      "/SERVICES/SIGNAGE/Display Sign.jpg",
      "/SERVICES/SIGNAGE/Hospital Sign.jpeg",
      "/SERVICES/SIGNAGE/Way Find Sign.jpg",
      "/SERVICES/SIGNAGE/Wheel Sign.jpg",
    ],
  },
  {
    title: "EVENT - ADDITIONAL SERVICES",
    subtitle: "Complete Visual Solutions for Events and Specialized Signage",
    icon: <Sparkles size={24} />,
    content: [
      "At Blackantz Creatives, we go beyond standard branding to deliver complete visual solutions for events and specialized signage needs. Our services are designed to create strong brand visibility across every touchpoint, ensuring your business stands out in any environment.",
      "We provide modern signage solutions including contemporary sign boards, pylon signs, and totem signs that enhance outdoor branding and create a bold visual presence. Each design is crafted to be impactful, durable, and aligned with your brand identity.",
      "Our expertise also includes hospital signage systems that focus on clarity, accessibility, and way finding. We design signage that improves navigation while maintaining a professional and organized visual environment.",
      "For mobile branding, we offer high-quality vehicle stickers and wraps that transform your vehicles into moving advertisements. These designs are eye-catching, durable, and effective in increasing brand reach across locations.",
      "In addition, we support events with customized branding elements such as banners, backdrops, and display setups. From concept to execution, our goal is to deliver creative solutions that elevate your brand experience and ensure maximum visibility.",
    ]
  },
];
